package Presentacion;

import java.awt.Color;
import java.awt.Graphics;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Luis García Estrades https://github.com/lgarest
 */
public class VistaOperadorPrincipal extends javax.swing.JFrame {
    CtrlPresentacion ctrlp;
    private String nombreCiudad;
    private String fecha;
    private String fechaCD;
    private String nombreRuta = new String();
    private String anadir;
    private String[] fechaHoy;
    private boolean advertencia;
    private ArrayList<String> listaPendientesS;
    private ArrayList<String> listaRutasS = new ArrayList<String>();
    private ArrayList<String> listaEnRutaS = new ArrayList<String>();
        
    /**
     * Creates new form VistaOperadorPrincipal
     */
    public VistaOperadorPrincipal() {
        initComponents();
        
    }
    // <editor-fold defaultstate="collapsed" desc="public VistaOperadorPrincipal(final CtrlPresentacion ctrlp)">  
    /**
     * Creates new form VistaOperadorPrincipal
     */
    public VistaOperadorPrincipal(final CtrlPresentacion ctrlp) throws IOException, FileNotFoundException, ClassNotFoundException {
        this.ctrlp = ctrlp;
        initComponents();
        advertencia = false;
        fechaHoy = ctrlp.fechaHoy();
        fecha = fechaHoy[0] + '/' + fechaHoy[1] + '/' + fechaHoy[2];
        fechaCD = fechaHoy[0] + '.' + fechaHoy[1] + '.' + fechaHoy[2];
        if (fechaHoy[3].equals("M")) {
            fecha = fecha + "-" + "M";
            fechaCD = fechaCD + "-" + "M";
        }
        else {
            fecha = fecha + "-" + "T";
            fechaCD = fechaCD + "-" + "T";
        }
        labelTurno.setText(fecha);
    }
    // </editor-fold>

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaRutas = new javax.swing.JList();
        btnModificarRuta = new javax.swing.JButton();
        btnValidarRuta = new javax.swing.JButton();
        btnCompararRutas = new javax.swing.JButton();
        btnEliminarRuta = new javax.swing.JButton();
        panelProximaRuta = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaEnRuta = new javax.swing.JList();
        accionesPanel = new javax.swing.JPanel();
        btnAnadirPaquete = new javax.swing.JButton();
        btnEliminarPaquete = new javax.swing.JButton();
        btnRutaRapida = new javax.swing.JButton();
        btnVerPaquetes = new javax.swing.JButton();
        btnRutaOptima = new javax.swing.JButton();
        btnRutaRapOptima = new javax.swing.JButton();
        panelInfo = new javax.swing.JPanel();
        panelTurno = new javax.swing.JPanel();
        labelTurno = new javax.swing.JLabel();
        panelCiudad = new javax.swing.JPanel();
        labelCiudad = new javax.swing.JLabel();
        btnVerMapa = new javax.swing.JButton();
        btnAyuda = new javax.swing.JButton();
        panelPendientes = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaPendientes = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 710));
        setPreferredSize(new java.awt.Dimension(800, 710));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Rutas", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        listaRutas.setModel(new javax.swing.AbstractListModel() {
            String[] strings = {  };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listaRutas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listaRutas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaRutasMouseClicked(evt);
            }
        });
        listaRutas.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                listaRutasAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(listaRutas);

        btnModificarRuta.setBackground(new java.awt.Color(75, 75, 75));
        btnModificarRuta.setForeground(new java.awt.Color(220, 220, 220));
        btnModificarRuta.setText("Ver / Mod");
        btnModificarRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarRutaActionPerformed(evt);
            }
        });

        btnValidarRuta.setBackground(new java.awt.Color(75, 75, 75));
        btnValidarRuta.setForeground(new java.awt.Color(220, 220, 220));
        btnValidarRuta.setText("Validar");
        btnValidarRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidarRutaActionPerformed(evt);
            }
        });

        btnCompararRutas.setBackground(new java.awt.Color(75, 75, 75));
        btnCompararRutas.setForeground(new java.awt.Color(220, 220, 220));
        btnCompararRutas.setText("Comparar");
        btnCompararRutas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompararRutasActionPerformed(evt);
            }
        });

        btnEliminarRuta.setBackground(new java.awt.Color(75, 75, 75));
        btnEliminarRuta.setForeground(new java.awt.Color(220, 220, 220));
        btnEliminarRuta.setText("Eliminar");
        btnEliminarRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarRutaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnValidarRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnModificarRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(btnCompararRutas, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnEliminarRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCompararRutas, btnEliminarRuta, btnModificarRuta, btnValidarRuta});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnModificarRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnValidarRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCompararRutas, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addComponent(btnEliminarRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1)))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnCompararRutas, btnEliminarRuta, btnModificarRuta, btnValidarRuta});

        panelProximaRuta.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Paquetes en la ruta", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        listaEnRuta.setModel(new javax.swing.AbstractListModel() {
            String[] strings = {  };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listaEnRuta.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listaEnRuta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaEnRutaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(listaEnRuta);

        javax.swing.GroupLayout panelProximaRutaLayout = new javax.swing.GroupLayout(panelProximaRuta);
        panelProximaRuta.setLayout(panelProximaRutaLayout);
        panelProximaRutaLayout.setHorizontalGroup(
            panelProximaRutaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
        );
        panelProximaRutaLayout.setVerticalGroup(
            panelProximaRutaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelProximaRutaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2))
        );

        accionesPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Acciones", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        btnAnadirPaquete.setBackground(new java.awt.Color(75, 75, 75));
        btnAnadirPaquete.setForeground(new java.awt.Color(220, 220, 220));
        btnAnadirPaquete.setText(">");
        btnAnadirPaquete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnadirPaqueteActionPerformed(evt);
            }
        });

        btnEliminarPaquete.setBackground(new java.awt.Color(75, 75, 75));
        btnEliminarPaquete.setForeground(new java.awt.Color(220, 220, 220));
        btnEliminarPaquete.setText("<");
        btnEliminarPaquete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarPaqueteActionPerformed(evt);
            }
        });

        btnRutaRapida.setBackground(new java.awt.Color(75, 75, 75));
        btnRutaRapida.setForeground(new java.awt.Color(220, 220, 220));
        btnRutaRapida.setText("Ruta rap.");
        btnRutaRapida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRutaRapidaActionPerformed(evt);
            }
        });

        btnVerPaquetes.setBackground(new java.awt.Color(75, 75, 75));
        btnVerPaquetes.setForeground(new java.awt.Color(220, 220, 220));
        btnVerPaquetes.setText("Ver PKT");
        btnVerPaquetes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerPaquetesActionPerformed(evt);
            }
        });

        btnRutaOptima.setBackground(new java.awt.Color(75, 75, 75));
        btnRutaOptima.setForeground(new java.awt.Color(220, 220, 220));
        btnRutaOptima.setText("Ruta opt.");
        btnRutaOptima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRutaOptimaActionPerformed(evt);
            }
        });

        btnRutaRapOptima.setBackground(new java.awt.Color(75, 75, 75));
        btnRutaRapOptima.setForeground(new java.awt.Color(220, 220, 220));
        btnRutaRapOptima.setText("Ruta rap. opt.");
        btnRutaRapOptima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRutaRapOptimaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout accionesPanelLayout = new javax.swing.GroupLayout(accionesPanel);
        accionesPanel.setLayout(accionesPanelLayout);
        accionesPanelLayout.setHorizontalGroup(
            accionesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accionesPanelLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(accionesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAnadirPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(accionesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(btnVerPaquetes, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnRutaOptima, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnRutaRapida, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnEliminarPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnRutaRapOptima, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(4, 4, 4))
        );

        accionesPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAnadirPaquete, btnEliminarPaquete, btnRutaOptima, btnRutaRapOptima, btnRutaRapida, btnVerPaquetes});

        accionesPanelLayout.setVerticalGroup(
            accionesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accionesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAnadirPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminarPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRutaRapida, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRutaRapOptima, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRutaOptima, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVerPaquetes, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        accionesPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAnadirPaquete, btnEliminarPaquete, btnRutaOptima, btnRutaRapOptima, btnRutaRapida, btnVerPaquetes});

        panelInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Más información", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        panelTurno.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Turno", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        panelTurno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelTurnoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelTurnoLayout = new javax.swing.GroupLayout(panelTurno);
        panelTurno.setLayout(panelTurnoLayout);
        panelTurnoLayout.setHorizontalGroup(
            panelTurnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTurnoLayout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(labelTurno)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        panelTurnoLayout.setVerticalGroup(
            panelTurnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTurnoLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(labelTurno)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelCiudad.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ciudad", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        panelCiudad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelCiudadMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelCiudadLayout = new javax.swing.GroupLayout(panelCiudad);
        panelCiudad.setLayout(panelCiudadLayout);
        panelCiudadLayout.setHorizontalGroup(
            panelCiudadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCiudadLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(labelCiudad)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        panelCiudadLayout.setVerticalGroup(
            panelCiudadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCiudadLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(labelCiudad)
                .addGap(0, 14, Short.MAX_VALUE))
        );

        btnVerMapa.setBackground(new java.awt.Color(75, 75, 75));
        btnVerMapa.setForeground(new java.awt.Color(220, 220, 220));
        btnVerMapa.setText("Ver Mapa");
        btnVerMapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerMapaActionPerformed(evt);
            }
        });

        btnAyuda.setBackground(new java.awt.Color(75, 75, 75));
        btnAyuda.setForeground(new java.awt.Color(220, 220, 220));
        btnAyuda.setText("Ayuda");
        btnAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAyudaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelInfoLayout = new javax.swing.GroupLayout(panelInfo);
        panelInfo.setLayout(panelInfoLayout);
        panelInfoLayout.setHorizontalGroup(
            panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelTurno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVerMapa, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAyuda, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4))
        );

        panelInfoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAyuda, btnVerMapa});

        panelInfoLayout.setVerticalGroup(
            panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInfoLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelTurno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVerMapa, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAyuda, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelCiudad, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(2, 2, 2))
        );

        panelPendientes.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Paquetes pendientes", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        listaPendientes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listaPendientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaPendientesMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(listaPendientes);

        javax.swing.GroupLayout panelPendientesLayout = new javax.swing.GroupLayout(panelPendientes);
        panelPendientes.setLayout(panelPendientesLayout);
        panelPendientesLayout.setHorizontalGroup(
            panelPendientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
        );
        panelPendientesLayout.setVerticalGroup(
            panelPendientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPendientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelPendientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(accionesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelProximaRuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {panelPendientes, panelProximaRuta});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(accionesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelProximaRuta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelPendientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void setAdvertencia(boolean advertencia) {
        this.advertencia = advertencia;
    }
    
    public void setListaEnRutaS(ArrayList<String> listaEnRutaS) {
        this.listaEnRutaS = listaEnRutaS;
    }
    
    // <editor-fold defaultstate="collapsed" desc="private boolean comprobar(int idx)">  
    private boolean comprobar(int idx){
        int cont = 0;
        char[] charsRuta = nombreRuta.toCharArray();
        boolean encontrado = false;
        for(int i = 0; i < charsRuta.length && !encontrado; ++i){
            if(cont == 6){
                if(charsRuta[i+1] == 'V'){
                    return false;
                }
                else encontrado = true;
            }
            if(charsRuta[i] == '-'){
                ++cont;
            }
        }
        for(int i = 0; i < listaEnRutaS.size();++i){
            if(listaPendientesS.get(idx).equals(listaEnRutaS.get(i))){
                return false;
            }
        }
        return true;
    }
    // </editor-fold>
    
    // <editor-fold defaultstate="collapsed" desc="private void btnAnadirPaqueteActionPerformed(java.awt.event.ActionEvent evt)">  
    private void btnAnadirPaqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnadirPaqueteActionPerformed
        int idx = listaPendientes.getSelectedIndex();      
        anadir = (String) listaPendientes.getSelectedValue();
        if (anadir != null){
            boolean cambio = comprobar(idx);
            boolean noverificada = checkVerificada();
            if(cambio && noverificada){
                listaPendientesS.remove(idx);
                listaEnRutaS.add(anadir);
            }
            actualizarListaPendientes();
            actualizarListaEnRuta();
        }
    }//GEN-LAST:event_btnAnadirPaqueteActionPerformed
// </editor-fold>
    
    // <editor-fold defaultstate="collapsed" desc="private void panelMapaMouseClicked(java.awt.event.MouseEvent evt)">  
    private void panelMapaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMapaMouseClicked
        // TODO add your handling code here:
        if (ctrlp != null) try {
            ctrlp.iniVentanaSecundaria("verDibujoCiudad");
        } catch (IOException ex) {
            Logger.getLogger(VistaOperadorPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(VistaOperadorPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_panelMapaMouseClicked
    // </editor-fold>
    
    // <editor-fold defaultstate="collapsed" desc="private void panelTurnoMouseClicked(java.awt.event.MouseEvent evt)">  
    private void panelTurnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelTurnoMouseClicked
        if (ctrlp != null){
            try {
                ctrlp.iniVentanaSecundaria("vistaTurno");
            } catch (IOException ex) {
                Logger.getLogger(VistaOperadorPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(VistaOperadorPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
            nombreRuta = new String();
        }
    }//GEN-LAST:event_panelTurnoMouseClicked
    // </editor-fold>
    
    // <editor-fold defaultstate="collapsed" desc="private void panelCiudadMouseClicked(java.awt.event.MouseEvent evt)">  
    private void panelCiudadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCiudadMouseClicked
        if (ctrlp != null) try {
            ctrlp.iniVentanaSecundaria("vistaCiudad");
        } catch (IOException ex) {
            Logger.getLogger(VistaOperadorPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(VistaOperadorPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        ctrlp.actualizarVentanaSecundaria();
        nombreRuta = new String();
    }//GEN-LAST:event_panelCiudadMouseClicked
    // </editor-fold>
    
    // <editor-fold defaultstate="collapsed" desc="private void listaRutasMouseClicked(java.awt.event.MouseEvent evt)">  
    private void listaRutasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaRutasMouseClicked
        if (evt.getClickCount() == 2) {
            String ruta = (String) listaRutas.getSelectedValue();
            if(ruta == null)
                JOptionPane.showMessageDialog(rootPane, "!No se ha seleccionado la ruta!");
            else{
                ctrlp.setRuta(ruta);
                try {
                    ctrlp.iniVentanaSecundaria("vistaModificarRuta");
                } catch (IOException ex) {
                    Logger.getLogger(VistaOperadorPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(VistaOperadorPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_listaRutasMouseClicked
    // </editor-fold>
    
    // <editor-fold defaultstate="collapsed" desc="private boolean checkVerificada()">  
    private boolean checkVerificada(){
        int cont = 0;
        if(nombreRuta.isEmpty()) return true;
        char[] charsRuta = nombreRuta.toCharArray();
        boolean encontrado = false;
        for(int i = 0; i < charsRuta.length && !encontrado; ++i){
            if(cont == 6){
                if(charsRuta[i] == 'V'){
                    return false;
                }
                else encontrado = true;
            }
            if(charsRuta[i] == '-'){
                ++cont;
            }
        }
        return true;
    }
    // </editor-fold>
    
    // <editor-fold defaultstate="collapsed" desc="private boolean compruebaEliminar(int idx)e">  
    private boolean compruebaEliminar(int idx){
            for(int i = 0; i < listaPendientesS.size(); ++i){
                if(listaEnRutaS.get(idx).equals(listaPendientesS.get(i))){
                    return false;
                }
            }
        return true;
    }
    // </editor-fold>
    
    // <editor-fold defaultstate="collapsed" desc="private void btnEliminarPaqueteActionPerformed(java.awt.event.ActionEvent evt)">  
    private void btnEliminarPaqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPaqueteActionPerformed
        int idx = listaEnRuta.getSelectedIndex();      
        anadir = (String) listaEnRuta.getSelectedValue();
        if (anadir != null){
            boolean noverificada = checkVerificada();
            boolean cambio = compruebaEliminar(idx);
            if(cambio && noverificada){
                listaEnRutaS.remove(idx);
                listaPendientesS.add(anadir);
            }
            actualizarListaPendientes();
            actualizarListaEnRuta();
        }
    }//GEN-LAST:event_btnEliminarPaqueteActionPerformed
// </editor-fold>
    
    // <editor-fold defaultstate="collapsed" desc="private void listaPendientesMouseClicked(java.awt.event.MouseEvent evt">  
    private void listaPendientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaPendientesMouseClicked
        if (evt.getClickCount() == 2) {
            int idx = listaPendientes.getSelectedIndex();      
            anadir = (String) listaPendientes.getSelectedValue();
            boolean cambio = comprobar(idx);
            boolean noverificada = checkVerificada();
            if(cambio && noverificada){
                listaPendientesS.remove(idx);
                listaEnRutaS.add(anadir);
            }
            actualizarListaPendientes();
            actualizarListaEnRuta();
        }
    }//GEN-LAST:event_listaPendientesMouseClicked
    // </editor-fold>
    
    // <editor-fold defaultstate="collapsed" desc="private void listaEnRutaMouseClicked(java.awt.event.MouseEvent evt)e">  
    private void listaEnRutaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaEnRutaMouseClicked
        if (evt.getClickCount() == 2) {
            int idx = listaEnRuta.getSelectedIndex();      
            anadir = (String) listaEnRuta.getSelectedValue();
            boolean cambio = compruebaEliminar(idx);
            boolean noverificada = checkVerificada();
            if(cambio && noverificada){
                listaEnRutaS.remove(idx);
                listaPendientesS.add(anadir);
            }
            actualizarListaPendientes();
            actualizarListaEnRuta();
        }
    }//GEN-LAST:event_listaEnRutaMouseClicked
    // </editor-fold>
    
    // <editor-fold defaultstate="collapsed" desc="private void btnRutaRapidaActionPerformed(java.awt.event.ActionEvent evt)e">  
    private void btnRutaRapidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRutaRapidaActionPerformed
        if (!listaEnRutaS.isEmpty()) {
            ctrlp.eliminarRutaComp(nombreRuta, null);
            try {
                ctrlp.calcularRuta(listaEnRutaS, fechaCD, nombreCiudad, "rapidamente");
            } catch (IOException ex) {
                Logger.getLogger(VistaOperadorPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(VistaOperadorPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
            actualizarRutas();
        }
    }//GEN-LAST:event_btnRutaRapidaActionPerformed
    // </editor-fold>
    
    // <editor-fold defaultstate="collapsed" desc="private void btnValidarRutaActionPerformed(java.awt.event.ActionEvent evt)e">  
    private void btnValidarRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidarRutaActionPerformed
        int idx = listaRutas.getSelectedIndex();      
        String ruta = (String) listaRutas.getSelectedValue();
        if (ruta == null)
            JOptionPane.showMessageDialog(rootPane, "!No se ha seleccionado la ruta!");
        else{
            actualizarListaPendientes();
            actualizarRutas();
            if (listaPendientesS.size() != listaEnRutaS.size()) {
                try {
                    ctrlp.iniVentanaSecundaria("advertencia");
                } catch (IOException ex) {
                    Logger.getLogger(VistaOperadorPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(VistaOperadorPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
                if (advertencia) {
                    try {
                        ctrlp.paquetesEnviados(nombreRuta);
                    } catch (IOException ex) {
                        Logger.getLogger(VistaOperadorPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (ClassNotFoundException ex) {
                        Logger.getLogger(VistaOperadorPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    try {
                        ctrlp.aceptarRuta(ruta, fechaCD, nombreCiudad);
                    } catch (IOException ex) {
                        Logger.getLogger(VistaOperadorPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (ClassNotFoundException ex) {
                        Logger.getLogger(VistaOperadorPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                    }

                    listaPendientesS = ctrlp.getPaquetesPendientes(nombreCiudad, fechaCD);
                    actualizarListaPendientes();
                    actualizarRutas();
                }

            }
            else {
                try {
                    ctrlp.paquetesEnviados(nombreRuta);
                } catch (IOException ex) {
                    Logger.getLogger(VistaOperadorPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(VistaOperadorPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
                try {
                    ctrlp.aceptarRuta(ruta, fechaCD, nombreCiudad);
                } catch (IOException ex) {
                    Logger.getLogger(VistaOperadorPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(VistaOperadorPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }

                listaPendientesS = ctrlp.getPaquetesPendientes(nombreCiudad, fechaCD);
                actualizarListaPendientes();
                actualizarRutas();
            }
            listaPendientesS = ctrlp.getPaquetesPendientes(nombreCiudad, fechaCD);
            actualizarListaPendientes();
            actualizarRutas();
            advertencia = false;
        }
    }//GEN-LAST:event_btnValidarRutaActionPerformed
    // </editor-fold>
    
    // <editor-fold defaultstate="collapsed" desc="private void btnEliminarRutaActionPerformed(java.awt.event.ActionEvent evt)">  
    private void btnEliminarRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarRutaActionPerformed
        int idx = listaRutas.getSelectedIndex();      
        String ruta = (String) listaRutas.getSelectedValue();
        if (ruta != null) {
            actualizarListaPendientes();
            ctrlp.eliminarRuta(ruta);
            actualizarRutas();
            listaPendientesS = ctrlp.getPaquetesPendientes(nombreCiudad, fechaCD);
            actualizarListaPendientes();
            nombreRuta = new String();
            listaEnRutaS.removeAll(listaEnRutaS);
            actualizarListaEnRuta();
        }
    }//GEN-LAST:event_btnEliminarRutaActionPerformed
    // </editor-fold>
    
   // </editor-fold>
    
    // <editor-fold defaultstate="collapsed" desc="private void btnVerPaquetesActionPerformed(java.awt.event.ActionEvent evt) ">  
    private void btnVerPaquetesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerPaquetesActionPerformed
        try {
            ctrlp.iniVentanaSecundaria("vistaPaquetes");
        } catch (IOException ex) {
            Logger.getLogger(VistaOperadorPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(VistaOperadorPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnVerPaquetesActionPerformed
    // </editor-fold>
    
    // <editor-fold defaultstate="collapsed" desc="private void btnRutaOptimaActionPerformed(java.awt.event.ActionEvent evt)e">  
    private void btnRutaOptimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRutaOptimaActionPerformed
        if (!listaEnRutaS.isEmpty()) {
            ctrlp.eliminarRutaComp(nombreRuta, null);
            try {
                ctrlp.calcularRuta(listaEnRutaS, fechaCD, nombreCiudad, "lentamente");
            } catch (IOException ex) {
                Logger.getLogger(VistaOperadorPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(VistaOperadorPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
            actualizarRutas();
        }
    }//GEN-LAST:event_btnRutaOptimaActionPerformed
    // </editor-fold>
    
    // <editor-fold defaultstate="collapsed" desc="private void btnRutaRapOptimaActionPerformed(java.awt.event.ActionEvent evt)">  
    private void btnRutaRapOptimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRutaRapOptimaActionPerformed
        if (!listaEnRutaS.isEmpty()) {
            ctrlp.eliminarRutaComp(nombreRuta, null);
            try {
                ctrlp.calcularRuta(listaEnRutaS, fechaCD, nombreCiudad, "rapidaOptima");
            } catch (IOException ex) {
                Logger.getLogger(VistaOperadorPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(VistaOperadorPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
            actualizarRutas();
        }
    }//GEN-LAST:event_btnRutaRapOptimaActionPerformed
    // </editor-fold>
    
    // <editor-fold defaultstate="collapsed" desc="private void btnCompararRutasActionPerformed(java.awt.event.ActionEvent evt)">  
    private void btnCompararRutasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompararRutasActionPerformed
        listaPendientesS = ctrlp.getPaquetesPendientes(nombreCiudad, fechaCD);
        if (!listaEnRutaS.isEmpty()) {
            actualizarListaPendientes();
            ctrlp.eliminarRutaComp(nombreRuta, null);
            try {
                ctrlp.calcularRuta(listaEnRutaS, fechaCD, nombreCiudad, "lentamente");
            } catch (IOException ex) {
                Logger.getLogger(VistaOperadorPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(VistaOperadorPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                ctrlp.calcularRuta(listaEnRutaS, fechaCD, nombreCiudad, "rapidamente");
            } catch (IOException ex) {
                Logger.getLogger(VistaOperadorPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(VistaOperadorPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                ctrlp.calcularRuta(listaEnRutaS, fechaCD, nombreCiudad, "rapidaOptima");
            } catch (IOException ex) {
                Logger.getLogger(VistaOperadorPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(VistaOperadorPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                ctrlp.iniVentanaSecundaria("vistaCompararRutas");
            } catch (IOException ex) {
                Logger.getLogger(VistaOperadorPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(VistaOperadorPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
            actualizarListaEnRuta();
        }
    }//GEN-LAST:event_btnCompararRutasActionPerformed

    private void btnModificarRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarRutaActionPerformed
        String ruta = (String) listaRutas.getSelectedValue();
        if(ruta == null)
            JOptionPane.showMessageDialog(rootPane, "!No se ha seleccionado la ruta!");
        else{
            ctrlp.setRuta(ruta);
            try {
                ctrlp.iniVentanaSecundaria("vistaModificarRuta");
            } catch (IOException ex) {
                Logger.getLogger(VistaOperadorPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(VistaOperadorPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnModificarRutaActionPerformed

    private void btnVerMapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerMapaActionPerformed
        if (this.getCiudad()!=null)
            try {
            ctrlp.iniVentanaSecundaria("verDibujoCiudad");
        } catch (IOException ex) {
            Logger.getLogger(VistaOperadorPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(VistaOperadorPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        else
            JOptionPane.showMessageDialog(rootPane, "!No se ha seleccionado la ciudad!");
    }//GEN-LAST:event_btnVerMapaActionPerformed

    private void btnAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAyudaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAyudaActionPerformed

    private void listaRutasAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_listaRutasAncestorAdded
        if (!listaRutasS.isEmpty()) {
            int idx = listaRutas.getSelectedIndex();      
            nombreRuta = (String) listaRutas.getSelectedValue();
            listaPendientesS = ctrlp.getPaquetesPendientes(nombreCiudad, fechaCD);
            actualizarListaPendientes();
            try {
                mostrarPaquetesEnRuta();
            } catch (IOException ex) {
                Logger.getLogger(VistaOperadorPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(VistaOperadorPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_listaRutasAncestorAdded
// </editor-fold>
    
    // <editor-fold defaultstate="collapsed" desc="public void actualizarCiudad(String nombreCiudad) ">  
    public void actualizarCiudad(String nombreCiudad) {
        this.nombreCiudad = nombreCiudad;
        labelCiudad.setText(nombreCiudad);
        actualizarRutas();
        mostrarPaquetesTurno();
    }
    // </editor-fold>
    
    // <editor-fold defaultstate="collapsed" desc="public void actualizarRutas()e">  
    public void actualizarRutas() {
        listaRutasS = ctrlp.getRutas(nombreCiudad);
        listaRutas.setModel(new javax.swing.AbstractListModel() {
            ArrayList<String> strings = listaRutasS;
            public int getSize() { return strings.size(); }
            public Object getElementAt(int i) { return strings.get(i); }
        });
    }
    // </editor-fold>
    
    // <editor-fold defaultstate="collapsed" desc="public void actualizarDia(int dia, int mes, int ano, String Turno)">  
    public void actualizarDia(int dia, int mes, int ano, String Turno) {
        String dia1, mes1, ano1;
        if (dia < 10) {
            dia1 = '0' + Integer.toString(dia);
        }
        else dia1 = Integer.toString(dia);
        if (mes < 10) {
            mes1 = '0' + Integer.toString(mes);
        }
        else mes1 = Integer.toString(mes);
        if (ano < 10) {
            ano1 = '0' + Integer.toString(ano);
        }
        else ano1 = Integer.toString(ano);
        fecha = dia1 + '/' + mes + '/' + ano;
        fechaCD = dia1 + '.' + mes + '.' + ano;
        if (Turno.equals("M")) {
            fecha = fecha + "-" + "M";
            fechaCD = fechaCD + "-" + "M";
        }
        else {
            fecha = fecha + "-" + "T";
            fechaCD = fechaCD + "-" + "T";
        }
        labelTurno.setText(fecha);
        mostrarPaquetesTurno();
    }
    // </editor-fold>
    
    // <editor-fold defaultstate="collapsed" desc="private void mostrarPaquetesEnRuta()e">  
    private void mostrarPaquetesEnRuta() throws IOException, FileNotFoundException, ClassNotFoundException {
        listaEnRutaS = ctrlp.getPaquetesRuta(nombreRuta);
        actualizarListaEnRuta();
    }
    // </editor-fold>
    
    // <editor-fold defaultstate="collapsed" desc="private void mostrarPaquetesTurno()">  
    private void mostrarPaquetesTurno() {
        listaPendientesS = ctrlp.getPaquetesPendientes(nombreCiudad, fechaCD);
        actualizarListaPendientes();
    }
    // </editor-fold>
    
    // <editor-fold defaultstate="collapsed" desc="public static void main(String args[])">  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaOperadorPrincipal().setVisible(true);
            }
        });
    }
    // </editor-fold>
    
    // <editor-fold defaultstate="collapsed" desc="private void actualizarListaPendientes()">  
    private void actualizarListaPendientes() {
        listaPendientes.setModel(new javax.swing.AbstractListModel() {
                ArrayList<String> strings = listaPendientesS;
                public int getSize() { return strings.size(); }
                public Object getElementAt(int i) { return strings.get(i); }
            });
    }
    // </editor-fold>
    
    // <editor-fold defaultstate="collapsed" desc="private void actualizarListaEnRuta()e">  
    public void actualizarListaEnRuta() {
        listaEnRuta.setModel(new javax.swing.AbstractListModel() {
            ArrayList<String> strings = listaEnRutaS;
            public int getSize() { return strings.size(); }
            public Object getElementAt(int i) { return strings.get(i); }
        });
    }
    // </editor-fold>
    
    // <editor-fold defaultstate="collapsed" desc="public String getCiudad() ">  
    public String getCiudad() {
        return nombreCiudad;
    }
    
    public String getFecha() {
        return fechaCD;
    }


    // </editor-fold>
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel accionesPanel;
    private javax.swing.JButton btnAnadirPaquete;
    private javax.swing.JButton btnAyuda;
    private javax.swing.JButton btnCompararRutas;
    private javax.swing.JButton btnEliminarPaquete;
    private javax.swing.JButton btnEliminarRuta;
    private javax.swing.JButton btnModificarRuta;
    private javax.swing.JButton btnRutaOptima;
    private javax.swing.JButton btnRutaRapOptima;
    private javax.swing.JButton btnRutaRapida;
    private javax.swing.JButton btnValidarRuta;
    private javax.swing.JButton btnVerMapa;
    private javax.swing.JButton btnVerPaquetes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labelCiudad;
    private javax.swing.JLabel labelTurno;
    private javax.swing.JList listaEnRuta;
    private javax.swing.JList listaPendientes;
    private javax.swing.JList listaRutas;
    private javax.swing.JPanel panelCiudad;
    private javax.swing.JPanel panelInfo;
    private javax.swing.JPanel panelPendientes;
    private javax.swing.JPanel panelProximaRuta;
    private javax.swing.JPanel panelTurno;
    // End of variables declaration//GEN-END:variables

}
